exclude_paths:
  - README.md
  - config/**
  - jacococoverage/**
  - src/main/resources/static/js/site.js
  - src/test/**
  - src/main/java/lukuvinkit/Main.java
  - Demo_cheatsheet.md
  - docs/**
  - lib/**